package generator

// TODO: Potentially rename file and just store all constant values in this file.
var Races = []string{
	"Dragonborn",
	"Hill Dwarf",
	"Mountain Dwarf",
	"High Elf",
	"Wood Elf",
	"Drow",
	"Forest Gnome",
	"Rock Gnome",
	"Half-Elf",
	"Lightfoot Halfling",
	"Stout Halfling",
	"Half-Orc",
	"Human",
	"Tiefling",
	"Aarakocra",
	"Aasimar",
	"Air Genasi",
	"Bugbear",
	"Centaur",
	"Changeling",
	"Deep Gnome",
	"Duergar",
	"Earth Genasi",
	"Eladrin",
	"Fairy",
	"Firbolg",
	"Fire Genasi",
	"Githyanki",
	"Githzerai",
	"Goblin",
	"Goliath",
	"Harengon",
	"Hobgoblin",
	"Kenku",
	"Kobold",
	"Lizardfolk",
	"Minotaur",
	"Orc",
	"Satyr",
	"Sea Elf",
	"Shadar-kai",
	"Shifter",
	"Tabaxi",
	"Tortle",
	"Triton",
	"Water Genasi",
	"Yuan-ti",
	"Warforged",
}
